print("I am {}.".format("Mc Andrew Neil Badong"))
print("My spirit animal is {}." .format("Dove"))
print("because{}." .format("i can handle situation"))
print("When not in school {} ." .format("I am in my bed"))
print("I dream of being a/an {} in the future" .format("Seaman"))